# Generated by Django 5.1.2 on 2024-12-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0005_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_trending",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_post", "New_Post"),
                    ("like", "Like"),
                    ("comment", "Comment"),
                ],
                max_length=20,
            ),
        ),
    ]
